version: '3'
services:
  jenkins:
    build:
      context: ./services/jenkins
      dockerfile: Dockerfile
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "8080:8080"