FROM redislabs/redismod:latest

EXPOSE 6379

#COPY redis.conf /usr/local/etc/redis/redis.conf


# VOLUME /myredis/conf:/usr/local/etc/redis

#  -v /home/user/data:/data \
# -v /home/user/redis.conf:/usr/local/etc/redis/redis.conf

#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]